FROM node:16-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN rm -rf node_modules
RUN npm install --force
COPY . .
RUN npm run build
FROM nginx:latest
COPY --from=builder /app/dist/crudtuto-Front /usr/share/nginx/html
EXPOSE 80
